
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/CV' #change it according to your repository name



# Profile information
yourname: Rohit Patil  ## put your name
title: 'Software Developer &amp; Deep Learning Engineer'  ## your title
location: Pune , India


## Social Profiles
facebook: https://www.facebook.com/rohit.patil.77  ## your facebook account url
twitter: https://twitter.com/Rohitpatil5  ## your twitter account url
linkedin: https://www.linkedin.com/in/rohitrpatil/  ## your linkedin account url
#dribbble: http://www.dribble.com  ## you dribbble account url
#foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
